"""
World Model Training Script (Pure NumPy)

Reads trajectory.csv generated by Godot, trains a Multi-Layer Perceptron
that learns the forward dynamics mapping:
    [x, y, vx, vy, ax, ay] -> [next_x, next_y, next_vx, next_vy]

The trained weights are saved as models/world_model.json so Godot can load
them. We also report an *open-loop rollout error*: how far the model's
imagined trajectory drifts from reality after 10 / 20 steps — this is the
key metric that tells you how good the World Model actually is.
"""

import csv
import json
import os
import sys

import numpy as np

# Project root (parent of the training/ folder) so paths are correct
# no matter which directory the script is launched from.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
os.makedirs(MODELS_DIR, exist_ok=True)

sys.path.insert(0, os.path.dirname(__file__))
from mlp import MLP


def load_rows(csv_path):
    rows = []
    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({k: float(v) for k, v in row.items()})
    return rows


def build_xy(rows):
    X = np.array([[r["x"], r["y"], r["vx"], r["vy"], r["ax"], r["ay"]] for r in rows])
    y = np.array([[r["next_x"], r["next_y"], r["next_vx"], r["next_vy"]] for r in rows])
    return X, y


def predict_single(model, x_raw, X_mean, X_std, y_mean, y_std):
    x = (np.array(x_raw, dtype=float) - X_mean) / X_std
    y = model.forward(x.reshape(1, -1)).reshape(-1)
    return y * y_std + y_mean


def evaluate_rollout(rows, model, X_mean, X_std, y_mean, y_std, K):
    """Open-loop rollout: feed the model its own prediction for K steps and
    measure the average position error vs. the real trajectory at step K."""
    errs = []
    for i in range(len(rows) - K):
        s = np.array([rows[i]["x"], rows[i]["y"], rows[i]["vx"], rows[i]["vy"]], dtype=float)
        for step in range(K):
            a = [rows[i + step]["ax"], rows[i + step]["ay"]]
            s = predict_single(model, np.concatenate([s, a]), X_mean, X_std, y_mean, y_std)[:4]
        gt = np.array([rows[i + K]["x"], rows[i + K]["y"]], dtype=float)
        errs.append(float(np.linalg.norm(s[:2] - gt)))
    return float(np.mean(errs)) if errs else 0.0


def rollout_sample(rows, model, X_mean, X_std, y_mean, y_std, K, start=0):
    """A single representative open-loop rollout: returns predicted vs. true
    positions at every step, for plotting / visual inspection."""
    true_pts = []
    pred_pts = []
    s = np.array([rows[start]["x"], rows[start]["y"], rows[start]["vx"], rows[start]["vy"]], dtype=float)
    for step in range(K):
        true_pts.append([rows[start + step + 1]["x"], rows[start + step + 1]["y"]])
        a = [rows[start + step]["ax"], rows[start + step]["ay"]]
        s = predict_single(model, np.concatenate([s, a]), X_mean, X_std, y_mean, y_std)[:4]
        pred_pts.append([float(s[0]), float(s[1])])
    return true_pts, pred_pts


def main():
    csv_path = os.path.join(DATA_DIR, "trajectory.csv")
    if not os.path.exists(csv_path):
        print(f"训练数据不存在: {csv_path}")
        print("请先在 Godot 中运行项目，按 S 键导出轨迹数据。")
        return

    rows = load_rows(csv_path)
    X, y = build_xy(rows)
    print(f"Loaded {X.shape[0]} samples")

    # Normalization: zero mean, unit variance
    X_mean, X_std = X.mean(axis=0), X.std(axis=0) + 1e-8
    y_mean, y_std = y.mean(axis=0), y.std(axis=0) + 1e-8
    X_norm = (X - X_mean) / X_std
    y_norm = (y - y_mean) / y_std

    # Train / validation split
    split = int(0.9 * len(X_norm))
    X_train, X_val = X_norm[:split], X_norm[split:]
    y_train, y_val = y_norm[:split], y_norm[split:]

    # Train MLP. 用 Adam 优化器，并按验证集自动早停：数据少时很快收敛结束，
    # 数据多时多训，避免浪费时间也不会过拟合。
    n_samples = X.shape[0]
    epochs = 2000 if n_samples > 2000 else 1200
    model = MLP([6, 64, 64, 32, 4], lr=0.01, optimizer="adam")
    model.train(X_train, y_train, epochs=epochs, batch_size=64, X_val=X_val, y_val=y_val, patience=200)

    # Validation (single-step)
    pred_val = model.forward(X_val)
    val_loss = float(np.mean((pred_val - y_val) ** 2))
    print(f"Validation MSE (normalized): {val_loss:.6f}")
    pred_val_denorm = pred_val * y_std + y_mean
    y_val_denorm = y_val * y_std + y_mean
    val_loss_px = float(np.mean((pred_val_denorm[:, :2] - y_val_denorm[:, :2]) ** 2))
    print(f"Validation position MSE (pixels^2): {val_loss_px:.2f}")

    # Open-loop rollout (the World-Model quality metric)
    roll10 = evaluate_rollout(rows, model, X_mean, X_std, y_mean, y_std, 10)
    roll20 = evaluate_rollout(rows, model, X_mean, X_std, y_mean, y_std, 20)
    print(f"Open-loop rollout position error @10 steps: {roll10:.2f} px")
    print(f"Open-loop rollout position error @20 steps: {roll20:.2f} px")

    # Save model for Godot
    os.makedirs("models", exist_ok=True)
    model_data = {
        "input_mean": X_mean.tolist(),
        "input_std": X_std.tolist(),
        "output_mean": y_mean.tolist(),
        "output_std": y_std.tolist(),
        "layers": [{"W": w.tolist(), "b": b.tolist()} for w, b in zip(model.weights, model.biases)]
    }
    with open(os.path.join(MODELS_DIR, "world_model.json"), "w") as f:
        json.dump(model_data, f, indent=2)

    # Save metrics for reporting / resume
    metrics = {
        "n_samples": int(X.shape[0]),
        "val_mse_norm": val_loss,
        "val_pos_mse_px": val_loss_px,
        "rollout_pos_err_10": roll10,
        "rollout_pos_err_20": roll20,
        "architecture": [6, 64, 64, 32, 4]
    }
    with open(os.path.join(MODELS_DIR, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    # Loss history for plotting the learning curve
    with open(os.path.join(MODELS_DIR, "loss_history.json"), "w") as f:
        json.dump({"epochs": list(range(1, len(model.loss_history) + 1)),
                   "loss": model.loss_history}, f, indent=2)

    # A representative open-loop rollout sample (predicted vs. true positions)
    K_sample = min(30, max(1, len(rows) - 2))
    true_pts, pred_pts = rollout_sample(rows, model, X_mean, X_std, y_mean, y_std, K_sample)
    with open(os.path.join(MODELS_DIR, "rollout_sample.json"), "w") as f:
        json.dump({"true": true_pts, "pred": pred_pts, "steps": K_sample}, f, indent=2)

    print("Model saved to " + os.path.join(MODELS_DIR, "world_model.json"))
    print("Metrics saved to " + os.path.join(MODELS_DIR, "metrics.json"))
    print("Artifacts: loss_history.json, rollout_sample.json")


if __name__ == "__main__":
    main()
